### ISSUE TITLE
tripyrun world.topo.bathy.200407.3x21600x10800.jpg not found

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/tripyview#112]
tripyrun is looking for this high res image. By default only world.topo.bathy.200407.3x5400x2700.png is available. 
Workaround is to go to the dir where it's suposed to be, (for me /work/ab0246/a270092/software/tripyview/tripyview/backgrounds) and to do 

wget https://neo.gsfc.nasa.gov/archive/bluemarble/bmng/world_2km/world.topo.bathy.200407.3x21600x10800.jpg

Should we just add this one to github? it's about 26MB.

**Comment by patrickscholz** [comment]
@JanStreffing: I deleted that file from the repository, because the total repo became to large. By default it should not been used, because if you use that image as a background image for the land sea mask the output images become huge as well! However i can try to include a wget call in case it is asked for!

**Comment by patrickscholz** [comment]
did you try this in the 3dsphere notebook?
